---
title: "eds212_day2_activities"
author: "Michael Zargari"
date: "`r format(Sys.time(), '%d-%B-%Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
```

```{r}
func <- expression(x^2)

funcc <- D(func, "x")

x <- 3
eval(funcc)
```

```{r}
func <- expression(2 * (3*a + 2)^4 - 5)

funcc <- D(func, "a")

a <- 1.2
eval(funcc)
```

```{r}
func <- expression(-4*t / (t*2 + 1)^3)

funcc <- D(func, "t")

t <- 0
eval(funcc)
```

```{r}
ggplot (data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
          geom_point (aes(color = species)) +
          labs(x = "Penguin Bill Length",
               y = "Penguin Bill Depth",
               title = "Comparison of Penguin Bills and Depths")
```

```{r}
ggplot (data = penguins, aes(x = species, y = flipper_length_mm)) +
          geom_jitter (aes(color = species)) +
          labs(x = "Penguin Species",
               y = "Penguin Flipper Depth",
               title = "Comparison of Penguin Flipper Length between Species")
```

```{r}
ggplot (data = penguins, aes(x = species, y = flipper_length_mm)) +
          geom_point (aes(color = species)) +
          labs(x = "Penguin Species",
               y = "Penguin Flipper Depth",
               title = "Comparison of Penguin Flipper Length between Species")
```

